import { Routes } from '@angular/router';
import { DatosMascota } from './components/datos-mascota/datos-mascota';
import { DatosDuenos } from './components/datos-duenos/datos-duenos';
import { PaginaPrincipal } from './pagina-principal/pagina-principal';
import { Alimentos } from './alimentos/alimentos';
import { CriaderoPastor } from './criadero-pastor/criadero-pastor';
import { Accesorios } from './components/accesorios/accesorios';
import { Servicios } from './components/servicios/servicios';
import { Usuario } from './components/usuario/usuario';
import { Admin } from './components/admin/admin';
import { Clientes } from './components/clientes/clientes';
import { HistorialClinico } from './components/historial-clinico/historial-clinico';
import { Proveedores } from './components/proveedores/proveedores';
import { ListadoMedicamentos } from './components/listado-medicamentos/listado-medicamentos';
import { CarnetVacunacion } from './components/carnet-vacunacion/carnet-vacunacion';
import { AlimentosNupec } from './components/alimentos-nupec/alimentos-nupec';
import { AlimentosProplan } from './components/alimentos-proplan/alimentos-proplan';
import { AlimentosRoyalCanin } from './components/alimentos-royalcanin/alimentos-royalcanin';
import { AlimentosGanador } from './components/alimentos-ganador/alimentos-ganador';
import { AlimentosHills } from './components/alimentos-hills/alimentos-hills';
import { ServiciosVacunas } from './components/servicios-vacunas/servicios-vacunas';
import { ServiciosEsteticas } from './components/servicios-esteticas/servicios-esteticas';
import { ServiciosBanos } from './components/servicios-banos/servicios-banos';
import { ServiciosDesparasitaciones } from './components/servicios-desparasitaciones/servicios-desparasitaciones';


export const routes: Routes = [
    { path: 'admin', component: Admin },
    { path: 'mascota', component: DatosMascota },
    { path: 'duenos', component: DatosDuenos },
    { path: 'pagina-principal', component: PaginaPrincipal },
    { path: '', redirectTo: '/pagina-principal', pathMatch: 'full' },
    { path: 'alimentos', component: Alimentos },
    { path: 'alimentos-nupec', component: AlimentosNupec },
    { path: 'alimentos-proplan', component: AlimentosProplan },
    { path: 'alimentos-royalcanin', component: AlimentosRoyalCanin },
    { path: 'alimentos-ganador', component: AlimentosGanador },
    { path: 'alimentos-hills', component: AlimentosHills },
    { path: 'servicios-vacunas', component: ServiciosVacunas },
    { path: 'servicios-esteticas', component: ServiciosEsteticas },
    { path: 'servicios-banos', component: ServiciosBanos },
    { path: 'servicios-desparasitaciones', component: ServiciosDesparasitaciones },
    { path: 'criadero-pastor', component: CriaderoPastor },
    { path: 'accesorios', component: Accesorios },
    { path: 'servicios', component: Servicios },
    { path: 'usuario', component: Usuario },
    { path: 'clientes', component: Clientes },
    { path: 'historial-clinico', component: HistorialClinico },
    { path: 'proveedores', component: Proveedores },
    { path: 'listado-medicamentos', component: ListadoMedicamentos },
    { path: 'carnet-vacunacion', component: CarnetVacunacion },
];
